matrix:
    include:
       - language: julia
         julia: 0.7
         os: linux
       - language: julia
         julia: 1.0
         os: linux
       - language: julia
         julia: nightly
         os: linux

       - language: julia
         julia: 0.7
         os: osx
       - language: julia
         julia: 1.0
         os: osx
       - language: julia
         julia: nightly
         os: osx

    allow_failures:
       - julia: nightly

notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("BlackBoxOptimizationBenchmarking")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'